bearer = 'OTNlYWNlOGEtMzYyOS00NmFjLTllYmYtYjk2ZDBmZDVkNTEzMzRhNzNiNzMtNmI0_PF84_1eb65fdf-9643-417f-9974-ad72cae0e10f' # bot token
webhook_URL = 'http://a1f760bc.ngrok.io' # URL generated by ngrok
webhook_name = 'hook-13' # for webex teams
bot_id = 'Y2lzY29zcGFyazovL3VzL0FQUExJQ0FUSU9OL2Q5NGYyYjZmLTliZmMtNGIyZS1hNTM1LWUwMzIzYzdjYjUyMA'
